#Shamelessly copied from the Project Euler project
Meteor.startup ->
  dev_mode = true;

  if Problems.find().count() is 0
    if dev_mode is true
      Problems.insert
        title: "1"
        solution: "test"
        answers: []
        sortOrder: '01'
        draft: false
        activeFrom: new Date('2016-01-01 06:00:00')
        description: "
        If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
        <br /><br />
        Find the sum of all the multiples of 3 or 5 below 1000."
        description_sv: "
        Om vi listar alla naturliga tal under 10 som är multiplar av 3 eller 5 så får vi 3, 5, 6 och 9. Summan av dessa multiplar är 23.
        <br /><br />
        Hitta summan av alla multiplar av 3 eller 5 som är under 1000."

      Problems.insert
        title: "2"
        solution: "test"
        answers: []
        sortOrder: '02'
        draft: false
        activeFrom: new Date('2016-01-01 06:00:00')
        description: "
        Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
        <br /><br />
        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        <br /><br />
        By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."
        description_sv: "
        Varje nytt tal i Fibonnaci-serien genereras genom att addera de två föregående talen. Genom att starta med 1 och 2 kommer de första 10 talen bli:
        <br /><br />
        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        <br /><br />
        Hitta alla tal i Fibonacci-serien vars värde inte överskrider fyra miljoner, och ta fram summan av de jämna talen."

      Problems.insert
        title: "3"
        solution: "test"
        answers: []
        sortOrder: '03'
        draft: false
        activeFrom: new Date('2016-01-01 06:00:00')
        description: "
        The prime factors of 13195 are 5, 7, 13 and 29.
        <br /><br />
        What is the largest prime factor of the number 600851475143 ?"
        description_sv: "
        Primtalsfaktorerna av 13195 är 5, 7, 13 och 29.
        <br /><br />
        Vilket tal är den största primtalsfaktoren av 600851475143 ?
        "

      Problems.insert
        title: "4"
        solution: "test"
        answers: []
        sortOrder: '04'
        draft: false
        activeFrom: new Date('2016-01-01 06:00:00')
        description: "
        A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.
        <br /><br />
        Find the largest palindrome made from the product of two 3-digit numbers."
        description_sv: "
        Ett palindromtal läses likadant åt båda håll. Det största palindromtalet som finns av produkten mellan två 2-siffrorstal är 9009 (91 × 99).
        <br /><br />
        Hitta det största palindromtalet som finns av produkten mellan två 3-siffrorstal.
        "

      Problems.insert
        title: "5"
        solution: "test"
        answers: []
        sortOrder: '05'
        draft: false
        activeFrom: new Date('2016-01-01 06:00:00')
        description: "
        2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.
        <br /><br />
        What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?"
        description_sv: "
        2520 är det minsta talet som kan delas av talen 1-10 utan att det blir någon rest.
        <br /><br />
        Vad är det minsta positiva talet som är jämt delbart av alla tal från 1-20?
        "

      Problems.insert
        title: "6"
        solution: "test"
        answers: []
        sortOrder: '06'
        draft: false
        activeFrom: new Date('2016-01-01 06:00:00')
        description: "
        The sum of the squares of the first ten natural numbers is,
        <br /><br />
        1<sup>2</sup> + 2<sup>2</sup> + ... + 10<sup>2</sup> = 385
        <br />
        The square of the sum of the first ten natural numbers is,
        <br /><br />
        (1 + 2 + ... + 10)<sup>2</sup> = 55<sup>2</sup> = 3025
        <br />
        Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 − 385 = 2640.
        <br /><br />
        Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum."
        description_sv: "
        Summan av kvadratroterna av de första tio naturliga talen är;
        <br /><br />
        1<sup>2</sup> + 2<sup>2</sup> + ... + 10<sup>2</sup> = 385
        <br />
        Kvadratroten av summan av de första tio naturliga talen är;
        <br /><br />
        (1 + 2 + ... + 10)<sup>2</sup> = 55<sup>2</sup> = 3025
        <br />
        Skillnaden mellan summan av kvadratroterna av de första tio heltalen och kvadratroten av summan är 3025 - 385 = 2640.
        <br /><br />
        Hitta skillnaden mellan summan av kvadratroterna av de hundra första naturliga talen och kvadratroten av summan.
        "

      Problems.insert
        title: "7"
        solution: "test"
        answers: []
        sortOrder: '07'
        draft: false
        activeFrom: new Date('2016-01-01 06:00:00')
        description: "
        By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.
        <br /><br />
        What is the 10 001st prime number?"
        description_sv: "
        Genom att lista de första sex primtalen: 2, 3, 5, 7, 11 och 13, så kan vi se att det sjätte primtalet är 13.
        <br /><br />
        Vad är det 10 001:a primtalet?
        "

      Problems.insert
        title: "8"
        solution: "test"
        answers: []
        sortOrder: '08'
        draft: false
        activeFrom: new Date('2016-01-01 06:00:00')
        description: "The four adjacent digits in the 1000-digit number that have the greatest product are 9 × 9 × 8 × 9 = 5832. <code class='has-copy'>7316717653133062491922511967442657474235534919493496983520312774506326239578318016984801869478851843858615607891129494954595017379583319528532088055111254069874715852386305071569329096329522744304355766896648950445244523161731856403098711121722383113622298934233803081353362766142828064444866452387493035890729629049156044077239071381051585930796086670172427121883998797908792274921901699720888093776657273330010533678812202354218097512545405947522435258490771167055601360483958644670632441572215539753697817977846174064955149290862569321978468622482839722413756570560574902614079729686524145351004748216637048440319989000889524345065854122758866688116427171479924442928230863465674813919123162824586178664583591245665294765456828489128831426076900422421902267105562632111110937054421750694165896040807198403850962455444362981230987879927244284909188845801561660979191338754992005240636899125607176060588611646710940507754100225698315520005593572972571636269561882670428252483600823257530420752963450</code> Find the thirteen adjacent digits in the 1000-digit number that have the greatest product. What is the value of this product?"
        description_sv: "De fyra intilligande siffrorna i det 1000-siffriga talet som har den största produkten är 9 × 9 × 8 × 9 = 5832. <code class='has-copy'>7316717653133062491922511967442657474235534919493496983520312774506326239578318016984801869478851843858615607891129494954595017379583319528532088055111254069874715852386305071569329096329522744304355766896648950445244523161731856403098711121722383113622298934233803081353362766142828064444866452387493035890729629049156044077239071381051585930796086670172427121883998797908792274921901699720888093776657273330010533678812202354218097512545405947522435258490771167055601360483958644670632441572215539753697817977846174064955149290862569321978468622482839722413756570560574902614079729686524145351004748216637048440319989000889524345065854122758866688116427171479924442928230863465674813919123162824586178664583591245665294765456828489128831426076900422421902267105562632111110937054421750694165896040807198403850962455444362981230987879927244284909188845801561660979191338754992005240636899125607176060588611646710940507754100225698315520005593572972571636269561882670428252483600823257530420752963450</code> Hitta de tretton intilligande siffrorna i det 1000 siffror långa talet som har den största produkten. Vad är värdet av produkten?"

      Problems.insert
        title: "9"
        solution: "test"
        answers: []
        sortOrder: '09'
        draft: false
        activeFrom: new Date('2016-01-01 06:00:00')
        description: "
        A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,
        <br /><br />
        a<sup>2</sup> + b<sup>2</sup> = c<sup>2</sup>
        <br />
        For example, 3<sup>2</sup> + 4<sup>2</sup> = 9 + 16 = 25 = 5<sup>2</sup>.
        <br /><br />
        There exists exactly one Pythagorean triplet for which a + b + c = 1000.
        <br />
        Find the product abc."
        description_sv: "
        En pythagoreisk tripel är ett set av tre naturliga tal, a < b < c, där följande gäller,
        <br /><br />
        a<sup>2</sup> + b<sup>2</sup> = c<sup></sup>2
        <br />
        Till exempel, 3<sup>2</sup> + 4<sup>2</sup> = 9 + 16 = 25 = 5<sup>2</sup>.
        <br /><br />
        Det finns bara en pythagoreisk tripel där a + b + c = 1000.
        <br />
        Hitta produkten abc."

      Problems.insert
        title: "10"
        solution: "test"
        answers: []
        sortOrder: '10'
        draft: false
        activeFrom: new Date('2016-01-01 06:00:00')
        description: "
        The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.
        <br /><br />
        Find the sum of all the primes below two million."
        description_sv: "
        Summan av primtalen under 10 är 2 + 3 + 5 + 7 = 17.
        <br />< br/>
        Hitta summan av alla primtal under två miljoner."

      Problems.insert
        title: "11"
        solution: "test"
        answers: []
        sortOrder: '11'
        draft: false
        activeFrom: new Date('2016-01-01 06:00:00')
        description: "
        In the 20×20 grid below, four numbers along a diagonal line have been marked in red. <code>08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08<br />49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00<br />81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65<br />52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91<br />22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80<br />24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50<br />32 98 81 28 64 23 67 10 <i class='red'>26</i> 38 40 67 59 54 70 66 18 38 64 70<br />67 26 20 68 02 62 12 20 95 <i class='red'>63</i> 94 39 63 08 40 91 66 49 94 21<br />24 55 58 05 66 73 99 26 97 17 <i class='red'>78</i> 78 96 83 14 88 34 89 63 72<br />21 36 23 09 75 00 76 44 20 45 35 <i class='red'>14</i> 00 61 33 97 34 31 33 95<br />78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92<br />16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57<br />86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58<br />19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40<br />04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66<br />88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69<br />04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36<br />20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16<br />20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54<br />01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48</code> The product of these numbers is 26 × 63 × 78 × 14 = 1788696. <br /><br /> What is the greatest product of four adjacent numbers in the same direction (up, down, left, right, or diagonally) in the 20×20 grid?"
        description_sv: "
        I 20×20-rutnätet här under finns det fyra tal längs en diagonal linje som är markerat i rött. <code>08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08<br />49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00<br />81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65<br />52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91<br />22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80<br />24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50<br />32 98 81 28 64 23 67 10 <i class='red'>26</i> 38 40 67 59 54 70 66 18 38 64 70<br />67 26 20 68 02 62 12 20 95 <i class='red'>63</i> 94 39 63 08 40 91 66 49 94 21<br />24 55 58 05 66 73 99 26 97 17 <i class='red'>78</i> 78 96 83 14 88 34 89 63 72<br />21 36 23 09 75 00 76 44 20 45 35 <i class='red'>14</i> 00 61 33 97 34 31 33 95<br />78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92<br />16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57<br />86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58<br />19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40<br />04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66<br />88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69<br />04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36<br />20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16<br />20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54<br />01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48</code> Produkten av dessa tal är 26 × 63 × 78 × 14 = 1788696. <br /><br /> Vad är den största produkten av fyra intilliggande tal i samma riktning (upp, ner, vänster, höger eller diagonalt) i 20×20-rutnätet?"

      Problems.insert
        title: "12"
        solution: "test"
        answers: []
        sortOrder: '12'
        draft: false
        activeFrom: new Date('2016-01-01 06:00:00')
        description: "The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be: <br /><br /> 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ... <br /><br /> Let us list the factors of the first seven triangle numbers: <br /><br /><code class='center'>1: 1 <br />3: 1,3 <br />6: 1,2,3,6 <br />10: 1,2,5,10 <br />15: 1,3,5,15 <br />21: 1,3,7,21 <br />28: 1,2,4,7,14,28</code> We can see that 28 is the first triangle number to have over five divisors. <br /><br /> What is the value of the first triangle number to have over five hundred divisors?"
        description_sv: "Serien av triangelnummer genereras genom att addera de naturliga talen. Genom detta skulle det 7:e trinagelnumret bli 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. De första 10 termerna skulle bli: <br /><br /> 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ... <br /><br /> Låt oss lista faktorerna för de sju första triangelnumren: <br /><br /><code class='center'>1: 1 <br />3: 1,3 <br />6: 1,2,3,6 <br />10: 1,2,5,10 <br />15: 1,3,5,15 <br />21: 1,3,7,21 <br />28: 1,2,4,7,14,28</code> Vi kan se att 28 är det första triangelnumret som har över 5 faktorer. <br /><br /> Vad är värdet av det första triangelnumret som har över 500 faktorer?"

      Problems.insert
        title: "13"
        solution: "test"
        answers: []
        sortOrder: '13'
        draft: false
        activeFrom: new Date('2016-01-01 06:00:00')
        description: "Work out the first ten digits of the sum of the following one-hundred 50-digit numbers.<code class='has-copy has-array'>37107287533902102798797998220837590246510135740250<br />46376937677490009712648124896970078050417018260538<br />74324986199524741059474233309513058123726617309629<br />91942213363574161572522430563301811072406154908250<br />23067588207539346171171980310421047513778063246676<br />89261670696623633820136378418383684178734361726757<br />28112879812849979408065481931592621691275889832738<br />44274228917432520321923589422876796487670272189318<br />47451445736001306439091167216856844588711603153276<br />70386486105843025439939619828917593665686757934951<br />62176457141856560629502157223196586755079324193331<br />64906352462741904929101432445813822663347944758178<br />92575867718337217661963751590579239728245598838407<br />58203565325359399008402633568948830189458628227828<br />80181199384826282014278194139940567587151170094390<br />35398664372827112653829987240784473053190104293586<br />86515506006295864861532075273371959191420517255829<br />71693888707715466499115593487603532921714970056938<br />54370070576826684624621495650076471787294438377604<br />53282654108756828443191190634694037855217779295145<br />36123272525000296071075082563815656710885258350721<br />45876576172410976447339110607218265236877223636045<br />17423706905851860660448207621209813287860733969412<br />81142660418086830619328460811191061556940512689692<br />51934325451728388641918047049293215058642563049483<br />62467221648435076201727918039944693004732956340691<br />15732444386908125794514089057706229429197107928209<br />55037687525678773091862540744969844508330393682126<br />18336384825330154686196124348767681297534375946515<br />80386287592878490201521685554828717201219257766954<br />78182833757993103614740356856449095527097864797581<br />16726320100436897842553539920931837441497806860984<br />48403098129077791799088218795327364475675590848030<br />87086987551392711854517078544161852424320693150332<br />59959406895756536782107074926966537676326235447210<br />69793950679652694742597709739166693763042633987085<br />41052684708299085211399427365734116182760315001271<br />65378607361501080857009149939512557028198746004375<br />35829035317434717326932123578154982629742552737307<br />94953759765105305946966067683156574377167401875275<br />88902802571733229619176668713819931811048770190271<br />25267680276078003013678680992525463401061632866526<br />36270218540497705585629946580636237993140746255962<br />24074486908231174977792365466257246923322810917141<br />91430288197103288597806669760892938638285025333403<br />34413065578016127815921815005561868836468420090470<br />23053081172816430487623791969842487255036638784583<br />11487696932154902810424020138335124462181441773470<br />63783299490636259666498587618221225225512486764533<br />67720186971698544312419572409913959008952310058822<br />95548255300263520781532296796249481641953868218774<br />76085327132285723110424803456124867697064507995236<br />37774242535411291684276865538926205024910326572967<br />23701913275725675285653248258265463092207058596522<br />29798860272258331913126375147341994889534765745501<br />18495701454879288984856827726077713721403798879715<br />38298203783031473527721580348144513491373226651381<br />34829543829199918180278916522431027392251122869539<br />40957953066405232632538044100059654939159879593635<br />29746152185502371307642255121183693803580388584903<br />41698116222072977186158236678424689157993532961922<br />62467957194401269043877107275048102390895523597457<br />23189706772547915061505504953922979530901129967519<br />86188088225875314529584099251203829009407770775672<br />11306739708304724483816533873502340845647058077308<br />82959174767140363198008187129011875491310547126581<br />97623331044818386269515456334926366572897563400500<br />42846280183517070527831839425882145521227251250327<br />55121603546981200581762165212827652751691296897789<br />32238195734329339946437501907836945765883352399886<br />75506164965184775180738168837861091527357929701337<br />62177842752192623401942399639168044983993173312731<br />32924185707147349566916674687634660915035914677504<br />99518671430235219628894890102423325116913619626622<br />73267460800591547471830798392868535206946944540724<br />76841822524674417161514036427982273348055556214818<br />97142617910342598647204516893989422179826088076852<br />87783646182799346313767754307809363333018982642090<br />10848802521674670883215120185883543223812876952786<br />71329612474782464538636993009049310363619763878039<br />62184073572399794223406235393808339651327408011116<br />66627891981488087797941876876144230030984490851411<br />60661826293682836764744779239180335110989069790714<br />85786944089552990653640447425576083659976645795096<br />66024396409905389607120198219976047599490197230297<br />64913982680032973156037120041377903785566085089252<br />16730939319872750275468906903707539413042652315011<br />94809377245048795150954100921645863754710598436791<br />78639167021187492431995700641917969777599028300699<br />15368713711936614952811305876380278410754449733078<br />40789923115535562561142322423255033685442488917353<br />44889911501440648020369068063960672322193204149535<br />41503128880339536053299340368006977710650566631954<br />81234880673210146739058568557934581403627822703280<br />82616570773948327592232845941706525094512325230608<br />22918802058777319719839450180888072429661980811197<br />77158542502016545090413245809786882778948721859617<br />72107838435069186155435662884062257473692284509516<br />20849603980134001723930671666823555245252804609722<br />53503534226472524250874054075591789781264330331690</code>"
        description_sv: "Hitta de första 10 siffrorna av summan från följande 100 50-siffrorstal.<code class='has-copy has-array'>37107287533902102798797998220837590246510135740250<br />46376937677490009712648124896970078050417018260538<br />74324986199524741059474233309513058123726617309629<br />91942213363574161572522430563301811072406154908250<br />23067588207539346171171980310421047513778063246676<br />89261670696623633820136378418383684178734361726757<br />28112879812849979408065481931592621691275889832738<br />44274228917432520321923589422876796487670272189318<br />47451445736001306439091167216856844588711603153276<br />70386486105843025439939619828917593665686757934951<br />62176457141856560629502157223196586755079324193331<br />64906352462741904929101432445813822663347944758178<br />92575867718337217661963751590579239728245598838407<br />58203565325359399008402633568948830189458628227828<br />80181199384826282014278194139940567587151170094390<br />35398664372827112653829987240784473053190104293586<br />86515506006295864861532075273371959191420517255829<br />71693888707715466499115593487603532921714970056938<br />54370070576826684624621495650076471787294438377604<br />53282654108756828443191190634694037855217779295145<br />36123272525000296071075082563815656710885258350721<br />45876576172410976447339110607218265236877223636045<br />17423706905851860660448207621209813287860733969412<br />81142660418086830619328460811191061556940512689692<br />51934325451728388641918047049293215058642563049483<br />62467221648435076201727918039944693004732956340691<br />15732444386908125794514089057706229429197107928209<br />55037687525678773091862540744969844508330393682126<br />18336384825330154686196124348767681297534375946515<br />80386287592878490201521685554828717201219257766954<br />78182833757993103614740356856449095527097864797581<br />16726320100436897842553539920931837441497806860984<br />48403098129077791799088218795327364475675590848030<br />87086987551392711854517078544161852424320693150332<br />59959406895756536782107074926966537676326235447210<br />69793950679652694742597709739166693763042633987085<br />41052684708299085211399427365734116182760315001271<br />65378607361501080857009149939512557028198746004375<br />35829035317434717326932123578154982629742552737307<br />94953759765105305946966067683156574377167401875275<br />88902802571733229619176668713819931811048770190271<br />25267680276078003013678680992525463401061632866526<br />36270218540497705585629946580636237993140746255962<br />24074486908231174977792365466257246923322810917141<br />91430288197103288597806669760892938638285025333403<br />34413065578016127815921815005561868836468420090470<br />23053081172816430487623791969842487255036638784583<br />11487696932154902810424020138335124462181441773470<br />63783299490636259666498587618221225225512486764533<br />67720186971698544312419572409913959008952310058822<br />95548255300263520781532296796249481641953868218774<br />76085327132285723110424803456124867697064507995236<br />37774242535411291684276865538926205024910326572967<br />23701913275725675285653248258265463092207058596522<br />29798860272258331913126375147341994889534765745501<br />18495701454879288984856827726077713721403798879715<br />38298203783031473527721580348144513491373226651381<br />34829543829199918180278916522431027392251122869539<br />40957953066405232632538044100059654939159879593635<br />29746152185502371307642255121183693803580388584903<br />41698116222072977186158236678424689157993532961922<br />62467957194401269043877107275048102390895523597457<br />23189706772547915061505504953922979530901129967519<br />86188088225875314529584099251203829009407770775672<br />11306739708304724483816533873502340845647058077308<br />82959174767140363198008187129011875491310547126581<br />97623331044818386269515456334926366572897563400500<br />42846280183517070527831839425882145521227251250327<br />55121603546981200581762165212827652751691296897789<br />32238195734329339946437501907836945765883352399886<br />75506164965184775180738168837861091527357929701337<br />62177842752192623401942399639168044983993173312731<br />32924185707147349566916674687634660915035914677504<br />99518671430235219628894890102423325116913619626622<br />73267460800591547471830798392868535206946944540724<br />76841822524674417161514036427982273348055556214818<br />97142617910342598647204516893989422179826088076852<br />87783646182799346313767754307809363333018982642090<br />10848802521674670883215120185883543223812876952786<br />71329612474782464538636993009049310363619763878039<br />62184073572399794223406235393808339651327408011116<br />66627891981488087797941876876144230030984490851411<br />60661826293682836764744779239180335110989069790714<br />85786944089552990653640447425576083659976645795096<br />66024396409905389607120198219976047599490197230297<br />64913982680032973156037120041377903785566085089252<br />16730939319872750275468906903707539413042652315011<br />94809377245048795150954100921645863754710598436791<br />78639167021187492431995700641917969777599028300699<br />15368713711936614952811305876380278410754449733078<br />40789923115535562561142322423255033685442488917353<br />44889911501440648020369068063960672322193204149535<br />41503128880339536053299340368006977710650566631954<br />81234880673210146739058568557934581403627822703280<br />82616570773948327592232845941706525094512325230608<br />22918802058777319719839450180888072429661980811197<br />77158542502016545090413245809786882778948721859617<br />72107838435069186155435662884062257473692284509516<br />20849603980134001723930671666823555245252804609722<br />53503534226472524250874054075591789781264330331690</code>"

      Problems.insert
        title: "14"
        solution: "test"
        answers: []
        sortOrder: '14'
        draft: false
        activeFrom: new Date('2016-01-01 06:00:00')
        description: "
        The following iterative sequence is defined for the set of positive integers:
        <br /><br />
        n → n/2 (n is even)
        <br />
        n → 3n + 1 (n is odd)
        <br /><br />
        Using the rule above and starting with 13, we generate the following sequence:
        <br /><br />
        13 → 40 → 20 → 10 → 5 → 16 → 8 → 4 → 2 → 1
        <br />
        It can be seen that this sequence (starting at 13 and finishing at 1) contains 10 terms. Although it has not been proved yet (Collatz Problem), it is thought that all starting numbers finish at 1.
        <br /><br />
        Which starting number, under one million, produces the longest chain?
        <br /><br />
        NOTE: Once the chain starts the terms are allowed to go above one million."
        description_sv: "
        Följande serie är definierad för ett set av positiva nummer:
        <br /><br />
        n → n/2 (n är jämn)
        <br />
        n → 3n + 1 (n är udda)
        <br /><br />
        Genom att använda ovanstående regel och börja med 13 får vi fram följande serie:
        <br /><br />
        13 → 40 → 20 → 10 → 5 → 16 → 8 → 4 → 2 → 1
        <br />
        Man kan se att den här serien (som börjar på 13 och slutar på 1) innehåller 10 termer. Även fast det inte blivit bevisat än (Collatz problem), så är det tänkt att alla nummer slutar på 1.
        <br /><br />
        Vilket startnummer under en miljon genererar den längsta serien?
        <br /><br />
        NOTE: När serien påbörjats får termerna i serien överskrida en miljon."

      Problems.insert
        title: "15"
        solution: "test"
        answers: []
        sortOrder: '15'
        draft: false
        activeFrom: new Date('2016-01-01 06:00:00')
        description: "Starting in the top left corner of a 2×2 grid, and only being able to move to the right and down, there are exactly 6 routes to the bottom right corner. <img class='problem-img' src='/problem_15.gif' /> How many such routes are there through a 20×20 grid?"
        description_sv: "Om vi börjar i det övre vänstra hörnet av ett 2×2-rutnät, och bara får gå till höger och nedåt, så finns det sex vägar att ta till det nedre högra hörnet. <img class='problem-img' src='/problem_15.gif' /> Hur många vägar finns det genom ett 20×20-rutnät?"

      Problems.insert
        title: "16"
        solution: "test"
        answers: []
        sortOrder: '16'
        draft: false
        activeFrom: new Date('2016-01-01 06:00:00')
        description: "
        2<sup>15</sup> = 32768 and the sum of its digits is 3 + 2 + 7 + 6 + 8 = 26.
        <br /><br />
        What is the sum of the digits of the number 2<sup>1000</sup>?"
        description_sv: "
        2<sup>15</sup> = 32768 och summan av dess siffror är 3 + 2 + 7 + 6 + 8 = 26.
        <br /><br />
        Vad är summan av siffrorna för talet 2<sup>1000</sup>?"

      Problems.insert
        title: "17"
        solution: "test"
        answers: []
        sortOrder: '17'
        draft: false
        activeFrom: new Date('2016-01-01 06:00:00')
        description: "
        If the numbers 1 to 5 are written out in words: one, two, three, four, five, then there are 3 + 3 + 5 + 4 + 4 = 19 letters used in total.
        <br /><br />
        If all the numbers from 1 to 1000 (one thousand) inclusive were written out in words, how many letters would be used?
        <br /><br />
        NOTE: Do not count spaces or hyphens. For example, 342 (three hundred and forty-two) contains 23 letters and 115 (one hundred and fifteen) contains 20 letters. The use of ''and'' when writing out numbers is in compliance with British usage."
        description_sv: "
        Om siffrorna 1 till 5 är skrivna i ord (på engelska): one, two, three, four, five, så är det 3 + 3 + 5 + 4 + 4 = 19 bokstäver som används.
        <br /><br />
        Om alla nummer från 1 till 1000 skulle skrivas ut i ord (på engelska), hur många bokstäver skulle användas?
        <br /><br />
        NOTE: Räkna inte mellanslag, ''and'' eller bindesstreck. Till exempel 342 (three hundred and forty-two) innehåller 23 bokstäver och 115 (one hundred and fifteen) innehåller 20 bokstäver."

      Problems.insert
        title: "18"
        solution: "test"
        answers: []
        sortOrder: '18'
        draft: false
        activeFrom: new Date('2016-01-01 06:00:00')
        description: "By starting at the top of the triangle below and moving to adjacent numbers on the row below, the maximum total from top to bottom is 23.<code class='center'><i class='red'>3</i><br /> <i class='red'>7</i> 4<br /> 2 <i class='red'>4</i> 6<br /> 8 5 <i class='red'>9</i> 3</code>That is, 3 + 7 + 4 + 9 = 23. <br /><br /> Find the maximum total from top to bottom of the triangle below: <code class='center'>75<br /> 95 64<br /> 17 47 82<br /> 18 35 87 10<br /> 20 04 82 47 65<br /> 19 01 23 75 03 34<br /> 88 02 77 73 07 63 67<br /> 99 65 04 28 06 16 70 92<br /> 41 41 26 56 83 40 80 70 33<br /> 41 48 72 33 47 32 37 16 94 29<br /> 53 71 44 65 25 43 91 52 97 51 14<br /> 70 11 33 28 77 73 17 78 39 68 17 57<br /> 91 71 52 38 17 14 91 43 58 50 27 29 48<br /> 63 66 04 68 89 53 67 30 73 16 69 87 40 31<br /> 04 62 98 27 23 09 70 98 73 93 38 53 60 04 23</code> NOTE: As there are only 16384 routes, it is possible to solve this problem by trying every route. :)"
        description_sv: "Genom att starta på toppen av pyramiden här nedanför och flytta till intilliggande siffror på raden under så är 23 den högsta summan vi kan få fram.<code class='center'><i class='red'>3<br /> <i class='red'>7</i> 4<br /> 2 <i class='red'>4</i> 6<br /> 8 5 <i class='red'>9</i> 3</code>3 + 7 + 4 + 9 = 23. <br /><br /> Hitta den största summan från följande pyramid: <code class='center'>75<br /> 95 64<br /> 17 47 82<br /> 18 35 87 10<br /> 20 04 82 47 65<br /> 19 01 23 75 03 34<br /> 88 02 77 73 07 63 67<br /> 99 65 04 28 06 16 70 92<br /> 41 41 26 56 83 40 80 70 33<br /> 41 48 72 33 47 32 37 16 94 29<br /> 53 71 44 65 25 43 91 52 97 51 14<br /> 70 11 33 28 77 73 17 78 39 68 17 57<br /> 91 71 52 38 17 14 91 43 58 50 27 29 48<br /> 63 66 04 68 89 53 67 30 73 16 69 87 40 31<br /> 04 62 98 27 23 09 70 98 73 93 38 53 60 04 23</code> NOTE: Eftersom det endast finns 16384 vägar, så är det fullt möjligt att lösa detta problem genom att pröva varenda väg. :)"

      Problems.insert
        title: "19"
        solution: "test"
        answers: []
        sortOrder: '19'
        draft: false
        activeFrom: new Date('2016-01-01 06:00:00')
        description: "
        You are given the following information, but you may prefer to do some research for yourself.
        <br />
        1 Jan 1900 was a Monday.<br /><br />
        Thirty days has September,<br />
        April, June and November.<br />
        All the rest have thirty-one,<br />
        Saving February alone,<br />
        Which has twenty-eight, rain or shine.<br />
        And on leap years, twenty-nine.<br /><br />
        A leap year occurs on any year evenly divisible by 4, but not on a century unless it is divisible by 400.<br />
        How many Sundays fell on the first of the month during the twentieth century (1 Jan 1901 to 31 Dec 2000)?"
        description_sv: "
        Du får följande information från oss, men om du vill kan du efterforska lite själv också.
        <br />
        1 januari 1900 var en måndag.<br /><br />
        Tretti' dagar har november,<br />
        april, juni och september.<br />
        Februari tju'åtta alén,<br />
        alla de övriga trettioen.<br /><br />
        Ett skottår ger februari en extra dag.<br /><br />
        Skottår infaller varje år som är jämnt delbart med 4, men inte på ett millennium om det inte är jämnt delbart med 400.<br />
        Hur många söndagar föll på den första i en månad under det andra millenniet? (1 januari 1901 till 31 december 2000)"

      Problems.insert
        title: "20"
        solution: "test"
        answers: []
        sortOrder: '20'
        draft: false
        activeFrom: new Date('2016-01-01 06:00:00')
        description: "
        n! means n × (n − 1) × ... × 3 × 2 × 1
        <br /><br />
        For example, 10! = 10 × 9 × ... × 3 × 2 × 1 = 3628800,
        <br />
        and the sum of the digits in the number 10! is 3 + 6 + 2 + 8 + 8 + 0 + 0 = 27.
        <br /><br />
        Find the sum of the digits in the number 100!"
        description_sv: "
        n! betyder n × (n − 1) × ... × 3 × 2 × 1
        <br /><br />
        Till exempel, 10! = 10 × 9 × ... × 3 × 2 × 1 = 3628800,
        <br />
        och summan av siffrorna i talet 10! är 3 + 6 + 2 + 8 + 8 + 0 + 0 = 27.
        <br /><br />
        Hitta summan av alla siffror i talet 100!"

      Problems.insert
        title: "21"
        solution: "test"
        answers: []
        sortOrder: '21'
        draft: false
        activeFrom: new Date('2016-01-01 06:00:00')
        description: "
        Let d(n) be defined as the sum of proper divisors of n (numbers less than n which divide evenly into n).
        <br />
        If d(a) = b and d(b) = a, where a ≠ b, then a and b are an amicable pair and each of a and b are called amicable numbers.
        <br /><br />
        For example, the proper divisors of 220 are 1, 2, 4, 5, 10, 11, 20, 22, 44, 55 and 110; therefore d(220) = 284. The proper divisors of 284 are 1, 2, 4, 71 and 142; so d(284) = 220.
        <br /><br />
        Evaluate the sum of all the amicable numbers under 10 000."
        description_sv: "
        Låt d(n) vara definierad som summan av faktorerna av n (siffror mindre än n som delas jämnt in till n).
        <br />
        Om d(a) = b och d(b) = a, där a ≠ b, så är a och b ett vänskapligt par och både a och b kallas för vänskapliga tal.
        <br /><br />
        Till exempel, faktorerna av 220 är 1, 2, 4, 5, 10, 11, 20, 22, 44, 55 och 110; därför blir d(220) = 284. Faktorerna av 284 är 1, 2, 4, 71 och 142; så d(284) = 220.
        <br /><br />
        Hitta summan av alla vänskapliga tal under 10 000."

      Problems.insert
        title: "22"
        solution: "test"
        answers: []
        sortOrder: '22'
        draft: false
        activeFrom: new Date('2016-01-01 06:00:00')
        description: "
        Using ''names.txt'' (https://projecteuler.net/project/resources/p022_names.txt) (right click and 'Save Link/Target As...'), a 46K text file containing over five-thousand first names, begin by sorting it into alphabetical order.
        <br />
        Then working out the alphabetical value for each name, multiply this value by its alphabetical position in the list to obtain a name score.
        <br /><br />
        For example, when the list is sorted into alphabetical order, COLIN, which is worth 3 + 15 + 12 + 9 + 14 = 53, is the 938th name in the list. So, COLIN would obtain a score of 938 × 53 = 49714.
        <br /><br />
        What is the total of all the name scores in the file?"
        description_sv: "
        Genom att använda ''names.txt'' (https://projecteuler.net/project/resources/p022_names.txt) (högerklicka och välj 'Spara länk som...'), en 46K stor textfile som innehåller över 5000 namn, börja med att sortera den i alfabetisk ordning.
        <br />
        Hämta ut det alfabetiska värdet för varje namn och multiplicera detta med namnets alfabetiska position i listan för att få fram en namnpoäng.
        <br /><br />
        Till exempel, när listan är sorterad i alfabetisk ordning kommer COLIN, vilket är värt 3 + 15 + 12 + 9 + 14 = 53, på 938:de plats i listan. Så COLIN skulle få namnpoängen 938 × 53 = 49714.
        <br /><br />
        Vad är summan av alla namnpoäng i filen?"

      Problems.insert
        title: "23"
        solution: "test"
        answers: []
        sortOrder: '23'
        draft: false
        activeFrom: new Date('2016-01-01 06:00:00')
        description: "
        A perfect number is a number for which the sum of its proper divisors is exactly equal to the number.
        <br />
        For example, the sum of the proper divisors of 28 would be 1 + 2 + 4 + 7 + 14 = 28, which means that 28 is a perfect number.
        <br /><br />
        A number n is called deficient if the sum of its proper divisors is less than n and it is called abundant if this sum exceeds n.
        <br /><br />
        As 12 is the smallest abundant number, 1 + 2 + 3 + 4 + 6 = 16, the smallest number that can be written as the sum of two abundant numbers is 24. By mathematical analysis, it can be shown that all integers greater than 28123 can be written as the sum of two abundant numbers. However, this upper limit cannot be reduced any further by analysis even though it is known that the greatest number that cannot be expressed as the sum of two abundant numbers is less than this limit.
        <br /><br />
        Find the sum of all the positive integers which cannot be written as the sum of two abundant numbers."
        description_sv: "
        Ett perfekt tal är ett tal för vilken summan av dess faktorer är exakt samma som talet.
        <br />
        Till exempel, summan av faktorern aför 28 skulle bli 1 + 2 + 4 + 7 + 14 = 28, vilket betyder att 28 är ett perfekt tal.
        <br /><br />
        Ett tal n kallas defekt om summan av dess faktorer är mindre än n och det kallas för rikt om summan överstiger n.
        <br /><br />
        12 är det minsta rika talet, 1 + 2 + 3 + 4 + 6 = 16, vilket gör att det minsta talet som kan skrivas som summan av två rika tal är 24.
        Matematisk analys säger att alla tal som är större än 28123 kan skrivas som summan av två rika tal.
        Denna gräns kan inte minskas ytterligare via analys, även fast man vet att det största talet som inte kan bli skrivet som summan av två rika tal är mindre än denna gräns.
        <br /><br />
        Hitta summan av alla positiva tal som inte kan skrivas som summan av två rika tal."

      Problems.insert
        title: "24"
        solution: "test"
        answers: []
        sortOrder: '24'
        draft: false
        activeFrom: new Date('2016-01-01 06:00:00')
        description: "
        A permutation is an ordered arrangement of objects. For example, 3124 is one possible permutation of the digits 1, 2, 3 and 4.
        <br />
        If all of the permutations are listed numerically or alphabetically, we call it lexicographic order. The lexicographic permutations of 0, 1 and 2 are:
        <br /><br />
        012, 021, 102, 120, 201, 210
        <br /><br />
        What is the millionth lexicographic permutation of the digits 0, 1, 2, 3, 4, 5, 6, 7, 8 and 9?"
        description_sv: "
        En permutation är ett ordnat urval av objekt. Till exempel är 3124 en möjlig permutation av siffrorna 1, 2, 3 och 4.
        <br />
        Om alla pemutationer är listade numeriskt eller alfabetiskt kallas det för lexikografisk ordning. De lexikografiska permutationerna av 0, 1 och 2 är:
        <br /><br />
        012, 021, 102, 120, 201, 210
        <br /><br />
        Vad är den miljonte lexikografiska permutationen av siffrorna 0, 1, 2, 3, 4, 5, 6, 7, 8 och 9?"

    else
      Problems.insert
        title: "1"
        solution: "233168"
        answers: []
        sortOrder: '01'
        draft: false
        activeFrom: new Date('2016-12-01 06:00:00')
        activeTo: new Date('2016-12-02 06:00:00')
        description: "
        If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

        Find the sum of all the multiples of 3 or 5 below 1000."

      Problems.insert
        title: "2"
        solution: "4613732"
        answers: []
        sortOrder: '02'
        draft: false
        activeFrom: new Date('2016-12-02 06:00:00')
        activeTo: new Date('2016-12-03 06:00:00')
        description: "
        Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

        By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."

      Problems.insert
        title: "3"
        solution: "6857"
        answers: []
        sortOrder: '03'
        draft: false
        activeFrom: new Date('2016-12-03 06:00:00')
        activeTo: new Date('2016-12-04 06:00:00')
        description: "
        The prime factors of 13195 are 5, 7, 13 and 29.

        What is the largest prime factor of the number 600851475143 ?"

      Problems.insert
        title: "4"
        solution: "906609"
        answers: []
        sortOrder: '04'
        draft: false
        activeFrom: new Date('2016-12-04 06:00:00')
        activeTo: new Date('2016-12-05 06:00:00')
        description: "
        A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.

        Find the largest palindrome made from the product of two 3-digit numbers."

      Problems.insert
        title: "5"
        solution: "232792560"
        answers: []
        sortOrder: '05'
        draft: false
        activeFrom: new Date('2016-12-05 06:00:00')
        activeTo: new Date('2016-12-06 06:00:00')
        description: "
        2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

        What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?"

      Problems.insert
        title: "6"
        solution: "25164150"
        answers: []
        sortOrder: '06'
        draft: false
        activeFrom: new Date('2016-12-06 06:00:00')
        activeTo: new Date('2016-12-07 06:00:00')
        description: "
        The sum of the squares of the first ten natural numbers is,

        12 + 22 + ... + 102 = 385
        The square of the sum of the first ten natural numbers is,

        (1 + 2 + ... + 10)2 = 552 = 3025
        Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 − 385 = 2640.

        Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum."

      Problems.insert
        title: "7"
        solution: "104743"
        answers: []
        sortOrder: '07'
        draft: false
        activeFrom: new Date('2016-12-07 06:00:00')
        activeTo: new Date('2016-12-08 06:00:00')
        description: "
        By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.

        What is the 10 001st prime number?"

      Problems.insert
        title: "8"
        solution: "23514624000"
        answers: []
        sortOrder: '08'
        draft: false
        activeFrom: new Date('2016-12-08 06:00:00')
        activeTo: new Date('2016-12-09 06:00:00')
        description: "
        The four adjacent digits in the 1000-digit number that have the greatest product are 9 × 9 × 8 × 9 = 5832.

        73167176531330624919225119674426574742355349194934
        96983520312774506326239578318016984801869478851843
        85861560789112949495459501737958331952853208805511
        12540698747158523863050715693290963295227443043557
        66896648950445244523161731856403098711121722383113
        62229893423380308135336276614282806444486645238749
        30358907296290491560440772390713810515859307960866
        70172427121883998797908792274921901699720888093776
        65727333001053367881220235421809751254540594752243
        52584907711670556013604839586446706324415722155397
        53697817977846174064955149290862569321978468622482
        83972241375657056057490261407972968652414535100474
        82166370484403199890008895243450658541227588666881
        16427171479924442928230863465674813919123162824586
        17866458359124566529476545682848912883142607690042
        24219022671055626321111109370544217506941658960408
        07198403850962455444362981230987879927244284909188
        84580156166097919133875499200524063689912560717606
        05886116467109405077541002256983155200055935729725
        71636269561882670428252483600823257530420752963450

        Find the thirteen adjacent digits in the 1000-digit number that have the greatest product. What is the value of this product?"

      Problems.insert
        title: "9"
        solution: "31875000"
        answers: []
        sortOrder: '09'
        draft: false
        activeFrom: new Date('2016-12-09 06:00:00')
        activeTo: new Date('2016-12-10 06:00:00')
        description: "
        A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,

        a2 + b2 = c2
        For example, 32 + 42 = 9 + 16 = 25 = 52.

        There exists exactly one Pythagorean triplet for which a + b + c = 1000.
        Find the product abc."

      Problems.insert
        title: "10"
        solution: "142913828922"
        answers: []
        sortOrder: '10'
        draft: false
        activeFrom: new Date('2016-12-10 06:00:00')
        activeTo: new Date('2016-12-11 06:00:00')
        description: "
        The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.

        Find the sum of all the primes below two million."

      Problems.insert
        title: "11"
        solution: "70600674"
        answers: []
        sortOrder: '11'
        draft: false
        activeFrom: new Date('2016-12-11 06:00:00')
        activeTo: new Date('2016-12-12 06:00:00')
        description: "
        In the 20×20 grid below, four numbers along a diagonal line have been marked in red.

        08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08
        49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00
        81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65
        52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91
        22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80
        24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50
        32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70
        67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21
        24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72
        21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 97 34 31 33 95
        78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92
        16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57
        86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58
        19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40
        04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66
        88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69
        04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36
        20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16
        20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54
        01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48

        The product of these numbers is 26 × 63 × 78 × 14 = 1788696.

        What is the greatest product of four adjacent numbers in the same direction (up, down, left, right, or diagonally) in the 20×20 grid?"

      Problems.insert
        title: "12"
        solution: "76576500"
        answers: []
        sortOrder: '12'
        draft: false
        activeFrom: new Date('2016-12-12 06:00:00')
        activeTo: new Date('2016-12-13 06:00:00')
        description: "
        The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

        1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

        Let us list the factors of the first seven triangle numbers:

        1: 1
        3: 1,3
        6: 1,2,3,6
        10: 1,2,5,10
        15: 1,3,5,15
        21: 1,3,7,21
        28: 1,2,4,7,14,28
        We can see that 28 is the first triangle number to have over five divisors.

        What is the value of the first triangle number to have over five hundred divisors?"

      Problems.insert
        title: "13"
        solution: "5537376230"
        answers: []
        sortOrder: '13'
        draft: false
        activeFrom: new Date('2016-12-13 06:00:00')
        activeTo: new Date('2016-12-14 06:00:00')
        description: "
        Work out the first ten digits of the sum of the following one-hundred 50-digit numbers.

        37107287533902102798797998220837590246510135740250
        46376937677490009712648124896970078050417018260538
        74324986199524741059474233309513058123726617309629
        91942213363574161572522430563301811072406154908250
        23067588207539346171171980310421047513778063246676
        89261670696623633820136378418383684178734361726757
        28112879812849979408065481931592621691275889832738
        44274228917432520321923589422876796487670272189318
        47451445736001306439091167216856844588711603153276
        70386486105843025439939619828917593665686757934951
        62176457141856560629502157223196586755079324193331
        64906352462741904929101432445813822663347944758178
        92575867718337217661963751590579239728245598838407
        58203565325359399008402633568948830189458628227828
        80181199384826282014278194139940567587151170094390
        35398664372827112653829987240784473053190104293586
        86515506006295864861532075273371959191420517255829
        71693888707715466499115593487603532921714970056938
        54370070576826684624621495650076471787294438377604
        53282654108756828443191190634694037855217779295145
        36123272525000296071075082563815656710885258350721
        45876576172410976447339110607218265236877223636045
        17423706905851860660448207621209813287860733969412
        81142660418086830619328460811191061556940512689692
        51934325451728388641918047049293215058642563049483
        62467221648435076201727918039944693004732956340691
        15732444386908125794514089057706229429197107928209
        55037687525678773091862540744969844508330393682126
        18336384825330154686196124348767681297534375946515
        80386287592878490201521685554828717201219257766954
        78182833757993103614740356856449095527097864797581
        16726320100436897842553539920931837441497806860984
        48403098129077791799088218795327364475675590848030
        87086987551392711854517078544161852424320693150332
        59959406895756536782107074926966537676326235447210
        69793950679652694742597709739166693763042633987085
        41052684708299085211399427365734116182760315001271
        65378607361501080857009149939512557028198746004375
        35829035317434717326932123578154982629742552737307
        94953759765105305946966067683156574377167401875275
        88902802571733229619176668713819931811048770190271
        25267680276078003013678680992525463401061632866526
        36270218540497705585629946580636237993140746255962
        24074486908231174977792365466257246923322810917141
        91430288197103288597806669760892938638285025333403
        34413065578016127815921815005561868836468420090470
        23053081172816430487623791969842487255036638784583
        11487696932154902810424020138335124462181441773470
        63783299490636259666498587618221225225512486764533
        67720186971698544312419572409913959008952310058822
        95548255300263520781532296796249481641953868218774
        76085327132285723110424803456124867697064507995236
        37774242535411291684276865538926205024910326572967
        23701913275725675285653248258265463092207058596522
        29798860272258331913126375147341994889534765745501
        18495701454879288984856827726077713721403798879715
        38298203783031473527721580348144513491373226651381
        34829543829199918180278916522431027392251122869539
        40957953066405232632538044100059654939159879593635
        29746152185502371307642255121183693803580388584903
        41698116222072977186158236678424689157993532961922
        62467957194401269043877107275048102390895523597457
        23189706772547915061505504953922979530901129967519
        86188088225875314529584099251203829009407770775672
        11306739708304724483816533873502340845647058077308
        82959174767140363198008187129011875491310547126581
        97623331044818386269515456334926366572897563400500
        42846280183517070527831839425882145521227251250327
        55121603546981200581762165212827652751691296897789
        32238195734329339946437501907836945765883352399886
        75506164965184775180738168837861091527357929701337
        62177842752192623401942399639168044983993173312731
        32924185707147349566916674687634660915035914677504
        99518671430235219628894890102423325116913619626622
        73267460800591547471830798392868535206946944540724
        76841822524674417161514036427982273348055556214818
        97142617910342598647204516893989422179826088076852
        87783646182799346313767754307809363333018982642090
        10848802521674670883215120185883543223812876952786
        71329612474782464538636993009049310363619763878039
        62184073572399794223406235393808339651327408011116
        66627891981488087797941876876144230030984490851411
        60661826293682836764744779239180335110989069790714
        85786944089552990653640447425576083659976645795096
        66024396409905389607120198219976047599490197230297
        64913982680032973156037120041377903785566085089252
        16730939319872750275468906903707539413042652315011
        94809377245048795150954100921645863754710598436791
        78639167021187492431995700641917969777599028300699
        15368713711936614952811305876380278410754449733078
        40789923115535562561142322423255033685442488917353
        44889911501440648020369068063960672322193204149535
        41503128880339536053299340368006977710650566631954
        81234880673210146739058568557934581403627822703280
        82616570773948327592232845941706525094512325230608
        22918802058777319719839450180888072429661980811197
        77158542502016545090413245809786882778948721859617
        72107838435069186155435662884062257473692284509516
        20849603980134001723930671666823555245252804609722
        53503534226472524250874054075591789781264330331690"

      Problems.insert
        title: "14"
        solution: "837799"
        answers: []
        sortOrder: '14'
        draft: false
        activeFrom: new Date('2016-12-14 06:00:00')
        activeTo: new Date('2016-12-15 06:00:00')
        description: "
        The following iterative sequence is defined for the set of positive integers:

        n → n/2 (n is even)
        n → 3n + 1 (n is odd)

        Using the rule above and starting with 13, we generate the following sequence:

        13 → 40 → 20 → 10 → 5 → 16 → 8 → 4 → 2 → 1
        It can be seen that this sequence (starting at 13 and finishing at 1) contains 10 terms. Although it has not been proved yet (Collatz Problem), it is thought that all starting numbers finish at 1.

        Which starting number, under one million, produces the longest chain?

        NOTE: Once the chain starts the terms are allowed to go above one million."

      Problems.insert
        title: "15"
        solution: "137846528820"
        answers: []
        sortOrder: '15'
        draft: false
        activeFrom: new Date('2016-12-15 06:00:00')
        activeTo: new Date('2016-12-16 06:00:00')
        description: "
        Starting in the top left corner of a 2×2 grid, and only being able to move to the right and down, there are exactly 6 routes to the bottom right corner.

        (bild)
        How many such routes are there through a 20×20 grid?"

      Problems.insert
        title: "16"
        solution: "1366"
        answers: []
        sortOrder: '16'
        draft: false
        activeFrom: new Date('2016-12-16 06:00:00')
        activeTo: new Date('2016-12-17 06:00:00')
        description: "
        215 = 32768 and the sum of its digits is 3 + 2 + 7 + 6 + 8 = 26.

        What is the sum of the digits of the number 21000?"

      Problems.insert
        title: "17"
        solution: "21124"
        answers: []
        sortOrder: '17'
        draft: false
        activeFrom: new Date('2016-12-17 06:00:00')
        activeTo: new Date('2016-12-18 06:00:00')
        description: "
        If the numbers 1 to 5 are written out in words: one, two, three, four, five, then there are 3 + 3 + 5 + 4 + 4 = 19 letters used in total.

        If all the numbers from 1 to 1000 (one thousand) inclusive were written out in words, how many letters would be used?


        NOTE: Do not count spaces or hyphens. For example, 342 (three hundred and forty-two) contains 23 letters and 115 (one hundred and fifteen) contains 20 letters. The use of ''and'' when writing out numbers is in compliance with British usage."

      Problems.insert
        title: "18"
        solution: "1074"
        answers: []
        sortOrder: '18'
        draft: false
        activeFrom: new Date('2016-12-18 06:00:00')
        activeTo: new Date('2016-12-19 06:00:00')
        description: "
        By starting at the top of the triangle below and moving to adjacent numbers on the row below, the maximum total from top to bottom is 23.

        3
        7 4
        2 4 6
        8 5 9 3

        That is, 3 + 7 + 4 + 9 = 23.

        Find the maximum total from top to bottom of the triangle below:

        75
        95 64
        17 47 82
        18 35 87 10
        20 04 82 47 65
        19 01 23 75 03 34
        88 02 77 73 07 63 67
        99 65 04 28 06 16 70 92
        41 41 26 56 83 40 80 70 33
        41 48 72 33 47 32 37 16 94 29
        53 71 44 65 25 43 91 52 97 51 14
        70 11 33 28 77 73 17 78 39 68 17 57
        91 71 52 38 17 14 91 43 58 50 27 29 48
        63 66 04 68 89 53 67 30 73 16 69 87 40 31
        04 62 98 27 23 09 70 98 73 93 38 53 60 04 23

        NOTE: As there are only 16384 routes, it is possible to solve this problem by trying every route. However, Problem 67, is the same challenge with a triangle containing one-hundred rows; it cannot be solved by brute force, and requires a clever method! ;o)"

      Problems.insert
        title: "19"
        solution: "171"
        answers: []
        sortOrder: '19'
        draft: false
        activeFrom: new Date('2016-12-19 06:00:00')
        activeTo: new Date('2016-12-20 06:00:00')
        description: "
        You are given the following information, but you may prefer to do some research for yourself.

        1 Jan 1900 was a Monday.
        Thirty days has September,
        April, June and November.
        All the rest have thirty-one,
        Saving February alone,
        Which has twenty-eight, rain or shine.
        And on leap years, twenty-nine.
        A leap year occurs on any year evenly divisible by 4, but not on a century unless it is divisible by 400.
        How many Sundays fell on the first of the month during the twentieth century (1 Jan 1901 to 31 Dec 2000)?"

      Problems.insert
        title: "20"
        solution: "648"
        answers: []
        sortOrder: '20'
        draft: false
        activeFrom: new Date('2016-12-20 06:00:00')
        activeTo: new Date('2016-12-21 06:00:00')
        description: "
        n! means n × (n − 1) × ... × 3 × 2 × 1

        For example, 10! = 10 × 9 × ... × 3 × 2 × 1 = 3628800,
        and the sum of the digits in the number 10! is 3 + 6 + 2 + 8 + 8 + 0 + 0 = 27.

        Find the sum of the digits in the number 100!"

      Problems.insert
        title: "21"
        solution: "31626"
        answers: []
        sortOrder: '21'
        draft: false
        activeFrom: new Date('2016-12-21 06:00:00')
        activeTo: new Date('2016-12-22 06:00:00')
        description: "
        Let d(n) be defined as the sum of proper divisors of n (numbers less than n which divide evenly into n).
        If d(a) = b and d(b) = a, where a ≠ b, then a and b are an amicable pair and each of a and b are called amicable numbers.

        For example, the proper divisors of 220 are 1, 2, 4, 5, 10, 11, 20, 22, 44, 55 and 110; therefore d(220) = 284. The proper divisors of 284 are 1, 2, 4, 71 and 142; so d(284) = 220.

        Evaluate the sum of all the amicable numbers under 10000."

      Problems.insert
        title: "22"
        solution: "871198282"
        answers: []
        sortOrder: '22'
        draft: false
        activeFrom: new Date('2016-12-22 06:00:00')
        activeTo: new Date('2016-12-23 06:00:00')
        description: "
        Using names.txt (https://projecteuler.net/project/resources/p022_names.txt) (right click and 'Save Link/Target As...'), a 46K text file containing over five-thousand first names, begin by sorting it into alphabetical order. Then working out the alphabetical value for each name, multiply this value by its alphabetical position in the list to obtain a name score.

        For example, when the list is sorted into alphabetical order, COLIN, which is worth 3 + 15 + 12 + 9 + 14 = 53, is the 938th name in the list. So, COLIN would obtain a score of 938 × 53 = 49714.

        What is the total of all the name scores in the file?"

      Problems.insert
        title: "23"
        solution: "4179871"
        answers: []
        sortOrder: '23'
        draft: false
        activeFrom: new Date('2016-12-23 06:00:00')
        activeTo: new Date('2016-12-24 06:00:00')
        description: "
        A perfect number is a number for which the sum of its proper divisors is exactly equal to the number. For example, the sum of the proper divisors of 28 would be 1 + 2 + 4 + 7 + 14 = 28, which means that 28 is a perfect number.

        A number n is called deficient if the sum of its proper divisors is less than n and it is called abundant if this sum exceeds n.

        As 12 is the smallest abundant number, 1 + 2 + 3 + 4 + 6 = 16, the smallest number that can be written as the sum of two abundant numbers is 24. By mathematical analysis, it can be shown that all integers greater than 28123 can be written as the sum of two abundant numbers. However, this upper limit cannot be reduced any further by analysis even though it is known that the greatest number that cannot be expressed as the sum of two abundant numbers is less than this limit.

        Find the sum of all the positive integers which cannot be written as the sum of two abundant numbers."

      Problems.insert
        title: "24"
        solution: "2783915460"
        answers: []
        sortOrder: '24'
        draft: false
        activeFrom: new Date('2016-12-24 06:00:00')
        activeTo: new Date('2016-12-25 06:00:00')
        description: "
        A permutation is an ordered arrangement of objects. For example, 3124 is one possible permutation of the digits 1, 2, 3 and 4. If all of the permutations are listed numerically or alphabetically, we call it lexicographic order. The lexicographic permutations of 0, 1 and 2 are:

        012   021   102   120   201   210

        What is the millionth lexicographic permutation of the digits 0, 1, 2, 3, 4, 5, 6, 7, 8 and 9?"

  # If we only have one user. Make him admin!
  if Meteor.users.find().count() is 1
    Meteor.users.update {}, {$set: {isAdmin: true}}
